# Uncomment this line to define a global platform for your project
platform :ios, '6.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'JYOffineCache' do

pod 'FMDB'
# pod 'FMDB/FTS'   # FMDB with FTS
# pod 'FMDB/standalone'   # FMDB with latest SQLite amalgamation source
# pod 'FMDB/standalone/FTS'   # FMDB with latest SQLite amalgamation source and FTS
# pod 'FMDB/SQLCipher'   # FMDB with SQLCipher

pod 'MJRefresh'
pod 'MJExtension'

pod 'SDWebImage', '~>3.7'
pod 'AFNetworking', '~>2.0'

end

target 'JYOffineCacheTests' do

end

target 'JYOffineCacheUITests' do

end

